disabled_rules: # rule identifiers to exclude from running
 - colon
 # - comma
 # - control_statement
 - identifier_name
 - trailing_whitespace
 - force_cast
 - shorthand_operator
 - redundant_string_enum_value
 - line_length
 - unused_optional_binding
 - vertical_parameter_alignment
 - redundant_optional_initialization
 - empty_enum_arguments
 - empty_parentheses_with_trailing_closure
 - opening_brace
 - cyclomatic_complexity
 - function_body_length
 - type_body_length
 - inclusive_language
#opt_in_rules: # some rules are only opt-in
 # - empty_count
  # Find all the available rules by running:
  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
 # - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
